import api from "./api.js";
const $=s=>document.querySelector(s), money=n=>new Intl.NumberFormat("fr-FR",{style:"currency",currency:"XOF",maximumFractionDigits:0}).format(+n||0);
let S={page:"dashboard",products:[],categories:[],sales:[],movements:[],d:null};
const toast=(m,err=false)=>{let t=$("#toast");t.textContent=m;t.className="toast show"+(err?" err":"");setTimeout(()=>t.className="toast",2500)};
async function load(){[S.d,S.products,S.categories,S.sales,S.movements]=await Promise.all([api.request("/dashboard"),api.request("/products"),api.request("/categories"),api.request("/sales"),api.request("/stock")])}
const head=(t,s,b="")=>`<div class="page-head"><div><small>KAMS STOCK / WORKSPACE</small><h1>${t}</h1><p>${s}</p></div><div>${b}</div></div>`;
const k=(l,v,m,i)=>`<div class="k"><span>${l}</span><i data-lucide="${i}"></i><b>${v}</b><small>${m}</small></div>`;
function dashboard(){let d=S.d;return head("Vue d'ensemble","La performance de votre activité, en un coup d'œil.",`<button class="btn ghost" id="refresh">↻ Actualiser</button> <button class="btn" id="sale">＋ Nouvelle vente</button>`)+`<div class="ks">${k("Chiffre d'affaires",money(d.kpis.todayRevenue),"Aujourd'hui","wallet")} ${k("Bénéfice",money(d.kpis.todayProfit),"Marge réalisée","trending-up")} ${k("Ventes",d.kpis.todaySales,"Aujourd'hui","receipt")} ${k("Stock faible",d.kpis.lowStock,d.kpis.lowStock?"Réapprovisionnement":"Tout est bon","triangle-alert")}</div><div class="cols"><div class="panel"><div class="ph"><b>Performance commerciale</b><small>7 derniers jours</small></div><canvas id="chart"></canvas></div><div class="panel"><div class="ph"><b>Alertes stock</b><small>À surveiller</small></div>${S.products.filter(p=>p.low_stock).slice(0,5).map(p=>`<div class="alert"><span>◈</span><div><b>${p.name}</b><small>${p.sku}</small></div><strong>${p.stock_quantity} ${p.unit}</strong></div>`).join("")||'<div class="empty">Aucune alerte 🎉</div>'}</div></div><div class="panel"><div class="ph"><b>Dernières ventes</b><button class="link" data-page="sales">Tout voir →</button></div>${rows(S.sales.slice(0,7))}</div>`}
function rows(a){return `<div class="table"><div class="tr th"><span>VENTE</span><span>CLIENT</span><span>PAIEMENT</span><span>TOTAL</span><span>BÉNÉFICE</span><span>DATE</span></div>${a.map(x=>`<div class="tr"><span><b>#${x.id}</b></span><span>${x.customer_name}</span><span><em>${x.payment_method}</em></span><span><b>${money(x.total)}</b></span><span class="ok">+${money(x.profit)}</span><span>${new Date(x.created_at).toLocaleString("fr-FR")}</span></div>`).join("")}</div>`}
function products(){return head("Produits","Catalogue, prix, marges et niveaux de stock.",`<button class="btn" id="product">＋ Nouveau produit</button>`)+`<div class="toolbar"><input id="search" placeholder="⌕  Rechercher nom ou SKU..."><select id="cat"><option value="">Toutes les catégories</option>${S.categories.map(c=>`<option value="${c.id}">${c.name}</option>`).join("")}</select></div><div class="panel">${`<div class="table"><div class="tr th"><span>PRODUIT</span><span>CATÉGORIE</span><span>ACHAT</span><span>VENTE</span><span>STOCK</span><span>MARGE</span></div>`+S.products.map(p=>`<div class="tr"><span><b>${p.name}</b><small>${p.sku}</small></span><span>${p.category_name||"—"}</span><span>${money(p.purchase_price)}</span><span>${money(p.selling_price)}</span><span class="${p.low_stock?"bad":"ok"}">${p.stock_quantity} ${p.unit}</span><span class="ok">${money(p.unit_margin)}</span></div>`).join("")+`</div>`}</div>`}
function stock(){return head("Mouvements","Traçabilité complète des entrées et sorties.",`<button class="btn" id="move">＋ Mouvement</button>`)+`<div class="panel">${`<div class="table"><div class="tr th"><span>PRODUIT</span><span>TYPE</span><span>QTÉ</span><span>UTILISATEUR</span><span>NOTE</span><span>DATE</span></div>`+S.movements.map(x=>`<div class="tr"><span><b>${x.product_name}</b><small>${x.sku}</small></span><span class="${x.type==="IN"?"ok":"bad"}">${x.type==="IN"?"ENTRÉE":"SORTIE"}</span><span>${x.quantity}</span><span>${x.user_name||"—"}</span><span>${x.note||"—"}</span><span>${new Date(x.created_at).toLocaleString("fr-FR")}</span></div>`).join("")+`</div>`}</div>`}
function sales(){return head("Ventes","Transactions, paiements et rentabilité.",`<button class="btn" id="sale">＋ Nouvelle vente</button>`)+`<div class="ks three">${k("CA affiché",money(S.sales.reduce((a,x)=>a+ +x.total,0)),"Période","banknote")} ${k("Bénéfice",money(S.sales.reduce((a,x)=>a+ +x.profit,0)),"Période","coins")} ${k("Transactions",S.sales.length,"Historique","receipt")}</div><div class="panel">${rows(S.sales)}</div>`}
function categories(){return head("Catégories","Organisez votre activité par département.",`<button class="btn" id="catnew">＋ Catégorie</button>`)+`<div class="catgrid">${S.categories.map(c=>`<div class="catcard"><div>▦</div><h3>${c.name}</h3><p>${c.description||"Sans description"}</p><b>${c.product_count} produits</b></div>`).join("")}</div>`}
function reports(){let rev=S.sales.reduce((a,x)=>a+ +x.total,0),pr=S.sales.reduce((a,x)=>a+ +x.profit,0);return head("Rapports & analyses","Transformez vos données en décisions.",`<button class="btn ghost" id="refresh">↻ Actualiser</button>`)+`<div class="ks">${k("CA",money(rev),"Historique chargé","bar-chart-3")} ${k("Bénéfice",money(pr),"Profit","coins")} ${k("Marge",rev?Math.round(pr/rev*100)+"%":"0%","Rentabilité","percent")} ${k("Produits",S.products.length,"Catalogue","package")}</div><div class="cols"><div class="panel"><div class="ph"><b>Valeur du stock</b></div>${S.products.map(p=>`<div class="stockline"><span>${p.name}</span><b>${money(p.stock_quantity*p.purchase_price)}</b></div>`).join("")}</div><div class="panel insight"><div>✦</div><h2>Insights KAMS</h2><p>${S.d.kpis.lowStock?`Vous avez <b>${S.d.kpis.lowStock} produits</b> sous leur seuil minimum. Pensez à réapprovisionner.`:"Votre stock est actuellement sain. Continuez à surveiller les produits à forte rotation."}</p></div></div>`}
function modal(title,html,done){$("#modal").innerHTML=`<div class="back"><div class="modal"><div class="mh"><b>${title}</b><button data-close>×</button></div>${html}</div></div>`;$("#modal").classList.remove("hidden");$("#modal form").onsubmit=done}
function productModal(){modal("Nouveau produit",`<form class="form"><input name="name" placeholder="Nom du produit" required><input name="sku" placeholder="SKU / référence" required><select name="category_id"><option value="">Catégorie</option>${S.categories.map(c=>`<option value="${c.id}">${c.name}</option>`).join("")}</select><input name="unit" value="pièce" placeholder="Unité"><input name="purchase_price" type="number" placeholder="Prix achat" required><input name="selling_price" type="number" placeholder="Prix vente" required><input name="stock_quantity" type="number" value="0" placeholder="Stock initial"><input name="min_stock" type="number" value="5" placeholder="Seuil minimum"><button class="btn">Créer le produit</button></form>`,async e=>{e.preventDefault();let d=Object.fromEntries(new FormData(e.target));for(let x of ["category_id","purchase_price","selling_price","stock_quantity","min_stock"])d[x]=d[x]?+d[x]:null;try{await api.request("/products",{method:"POST",body:JSON.stringify(d)});close();toast("Produit créé");await refresh()}catch(x){toast(x.message,true)}})}
function moveModal(){modal("Mouvement de stock",`<form class="form"><select name="product_id" required>${S.products.map(p=>`<option value="${p.id}">${p.name} — ${p.stock_quantity}</option>`).join("")}</select><select name="type"><option value="IN">Entrée</option><option value="OUT">Sortie</option></select><input name="quantity" type="number" min="1" value="1"><input name="note" placeholder="Motif / note"><button class="btn">Valider</button></form>`,async e=>{e.preventDefault();let d=Object.fromEntries(new FormData(e.target));d.product_id=+d.product_id;d.quantity=+d.quantity;try{await api.request("/stock",{method:"POST",body:JSON.stringify(d)});close();toast("Stock mis à jour");await refresh()}catch(x){toast(x.message,true)}})}
function saleModal(){let items=[];modal("Nouvelle vente",`<form id="sf"><input name="customer_name" value="Client comptoir"><select id="sp">${S.products.filter(p=>p.stock_quantity>0).map(p=>`<option value="${p.id}">${p.name} — ${money(p.selling_price)}</option>`).join("")}</select><button type="button" class="btn ghost" id="add">＋ Ajouter</button><div id="cart" class="cart"></div><input name="discount" type="number" value="0" placeholder="Remise"><h2 id="total">Total: 0 FCFA</h2><button class="btn">Encaisser</button></form>`,async e=>{e.preventDefault();if(!items.length)return toast("Panier vide",true);let d=Object.fromEntries(new FormData(e.target));d.discount=+d.discount;d.items=items;try{await api.request("/sales",{method:"POST",body:JSON.stringify(d)});close();toast("Vente enregistrée");await refresh()}catch(x){toast(x.message,true)}});let redraw=()=>{$("#cart").innerHTML=items.map(i=>`<div>${i.name} × ${i.quantity} <b>${money(i.price*i.quantity)}</b></div>`).join("")||"Panier vide";$("#total").textContent="Total: "+money(items.reduce((a,i)=>a+i.price*i.quantity,0))+" FCFA"};$("#add").onclick=()=>{let p=S.products.find(x=>x.id==$("#sp").value),i=items.find(x=>x.product_id==p.id);if(i)i.quantity++;else items.push({product_id:p.id,name:p.name,price:+p.selling_price,quantity:1});redraw()};redraw()}
function close(){$("#modal").classList.add("hidden")}
async function refresh(){await load();render()}
function render(){let f={dashboard,products,stock,sales,categories,reports}[S.page];$("#content").innerHTML=f();document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x.dataset.page===S.page));if(window.lucide)lucide.createIcons();if(S.page==="dashboard"&&window.Chart)new Chart($("#chart"),{type:"line",data:{labels:S.d.chart.map(x=>x.day),datasets:[{data:S.d.chart.map(x=>x.revenue),tension:.35,fill:true,borderWidth:3}]},options:{plugins:{legend:{display:false}},scales:{y:{grid:{color:"#eee"}},x:{grid:{display:false}}}}})}
document.addEventListener("click",e=>{let n=e.target.closest("[data-page]");if(n){S.page=n.dataset.page;render()}if(e.target.closest("#product"))productModal();if(e.target.closest("#move"))moveModal();if(e.target.closest("#sale"))saleModal();if(e.target.closest("#refresh"))refresh();if(e.target.closest("#catnew"))toast("Création de catégorie : prochaine itération");if(e.target.closest("[data-close]"))close()});
async function start(){if(!api.token)return;$("#login").classList.add("hidden");$("#app").classList.remove("hidden");try{await load();render()}catch(e){toast(e.message,true)}}
$("#loginForm").onsubmit=async e=>{e.preventDefault();try{let d=await api.login($("#email").value,$("#password").value);api.token=d.token;localStorage.setItem("kams_token",d.token);$("#login").classList.add("hidden");$("#app").classList.remove("hidden");await load();render()}catch(x){toast(x.message,true)}};$("#logout").onclick=()=>{localStorage.clear();location.reload()};start();